Several improvements and generalization
DanySK/build-check-deploy-gradle-action pull request #124
Opened 2022-05-27 09:30 UTC by gciatto

Breaking changes for @DanySK:
- [3f37e90c5b4c5264e50a78cc7ff2e2d4451fb666](https://github.com/DanySK/build-check-deploy-gradle-action/commit/3f37e90c5b4c5264e50a78cc7ff2e2d4451fb666)
- [03f7f20ac033f6f15e54b50fed3f7abd0084676a](https://github.com/DanySK/build-check-deploy-gradle-action/commit/03f7f20ac033f6f15e54b50fed3f7abd0084676a)

2022-05-27 11:09 UTC, DanySK reviewed
This is plain wrong.

2022-05-30 11:26 UTC, DanySK requested changes
A couple of changes to reify, but several ideas look very good.

2022-05-30 11:26 UTC, DanySK commented on action.yml
> +    default: 'gradle assemble --parallel'
revert this, the wrapper **must** always be used.

2022-05-30 11:26 UTC, DanySK commented on action.yml
> +        ORG_GRADLE_PROJECT_npmToken: ${{ inputs.npm-token }}
These are nice. I would also expose them as `NPM_REPO` and `NPM_TOKEN`, consistently with how we deal with all other variables

2022-05-30 11:26 UTC, DanySK commented on action.yml
> +        #
```suggestion
        # Gradle-specific exports, see: 
        # https://docs.gradle.org/current/userguide/build_environment.html#sec:project_properties
```

2022-05-30 11:26 UTC, DanySK commented on action.yml
> +      run: gradle --stop
to be reverted along with all the calls to unknown versions of gradle

2022-06-01 10:15 UTC, gciatto commented on action.yml
> +        #
Should I do something here?

2022-06-01 16:16 UTC, merged